name: Build Firefox Installer
env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Firefox Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install choco
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072 #TLS 1.2
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      
      - name: Install rclone
        run: |
          choco install rclone -y
          refreshenv

      - name: Install 7z
        run: |
          choco install 7zip.install-y
          refreshenv

      - name: Build Firefox Installer
        shell: pwsh
        run: |
          .\firefox-build.ps1
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: our_new_installer
          path: ${{ github.workspace }}
          if-no-files-found: warn

