name: Build Firefox Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Firefox Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PowerShell
        uses: microsoft/setup-powershell@v1.4.0
      
      - name: Build Firefox Installer
        shell: pwsh
        run: |
          .\firefox-build.ps1
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: our_new_installer
          path: .\our_new_installer.exe
